package com.java;

public class TestingException {

	public static void main(String[] args) {

		int a = 10;
		String s;
		/*try {
			System.out.println("Hello");
			System.out.println(10 / 0);
			System.out.println("Hi");
		} catch (Exception e) {
			System.out.println("I am in catch block");
		}*/

	}

}
